language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r test_requirements.txt
env:
- TEST_ENV=travis
script:
- flake8 . && travis_wait 50 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_99dd1c7c40fb_key -iv $encrypted_99dd1c7c40fb_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/.mdf/credentials/
- mv MDF_Connect_Client_tokens.json ~/.mdf/credentials/MDF_Connect_Client_tokens.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: PeTw4hgPe/UvQXjmYD7tT+4J1tOZKOHw5sLYegSZtnekKeLpjLZib0eZrAkzE5LFbRoRgXZ9z4Yn+hN3az4Z1GodXYcRrYrvRwe75oZMgxe5TvXpmE1lqv8nCvbDo2LJbkVTdn0fKRRfEl1W62RtYcyh+QwunUudHA9U2zOZLqSt4BeYMTOK4T5XyhZ5T1DYSBO8Dj28OFuemjwGkBMgZ5Z/+GqIJ1wZw2sKHKN+vkKj8NChPEzok+GX0R1CXgqvMMHPNJUx/69hZMuqxZciQICqhAstUw//ssTI6bzGHivbhObE5nlDqmBIPDD8tEG6p/XOOFtHx2a/R6KV+5wjzIs6sLiEz2QAG/qKm20jSHi8j585RqjgpBGC1g0FQ8k75E0oF8ls5unHFnDHPRWnPI0ifZ2qgYIUWdHC6dV4QF06Z1OYRHfOiyiLvuWIlKufKRM6aC84LEXxBS7Lq4MUZ+wKjGVf5EmSeJzYC+NXnBcnkFOx3KnImNDP9JuBwsgrFYRZhpvlwKdmCn1sw+iAuhco+nTKrzq5fK4vglE4zAMr81YgnLrVY3xJrz0G4wbQYvtxcFx84GaV6UiL1hfbuu4aBw3o6kuq5gxEaYg18MvsIZyIbQOpNuqRtQsHknRJSoLPvIEv8Rq6zA2twHI1MJXunjzsc0WaCm2Npt1ZpGk=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: j7SC/8c2QLy9zXcLEdbySmOVKE6x/9AzY/kBXIB9oFmZpRzIXg7va7nA07QC3BVQ+y6pNpAdqDGQStCyP+BMYXA/NOyaETAASOUWLX9larbqvS9/GLU87gZiPlhVwaTxaLWf65ge+qMbrqpud/jnlTy1hodrAkQtWj5i8yIwTSINNBfbwQG/iLHy4iHjyvxhs9PWr6Akv+u4EZ7j6JtILw6/JzTZeHKbwe6pFc4sBlt8TfZnhkrixuYazPbCJnWOwHSdO3aYtHCEr9+AT5VYzxJGbwRewCUBiQO8/UIzPG2vWrBTl0f6DoUHOi6p4k7iWkY96E0Fu5uFaWEL+I+kA12pdJp8DE1cSeu3v3tl4BR/QMNIJ8IXCBnJ/TCgprGNsTzO9GFPd0cHDQcqWr8xzw+83tQcXKTHgwf6vkNyw7YC0TPNSVO7OKe4WhDQeQ5TiZMcdXtILaPgLJauQJeSyncLTPgUSr9R/ZmXrrrZCdYizoIurrCuL1GHULnnuHgCxX/uZubbScqDhCq+zZBDOtsuu7iHGMansYXdNo70LZL5MvpPufYmvVvllwTe6Mho8zXcgMLHL21WtTzQ+Qtkj0h+yZHgiWav/zpqHqCuQIPkO06DAlJc1t4KRiqpGLWO+8AWsphmNejOTS4d7CZsnW8Vp6A9DSxuhWN9MPoenfs=
